### PR TITLE
INC-29 refactor: change routes

### PR DESCRIPTION
**Pull request by IrinaMartArm**

### CODE REVIEW

**Comment by oksivasilinka** [comment]
В проекте есть как минимум 4 ошибки: 

TS2307: Cannot find module '@/widgets/general/hook/useProfileForm' or its corresponding type declarations.

TS2339: Property 'profile' does not exist on type '{ favorites: { title: string; }; general: { title: string; }; logOut: { buttonNo: string; buttonYes: string; title: string; warning: string; }; passwordRecovery: { back: string; createTitle: string; emailError: string; ... 5 more ...; title: string; }; policy: { ...; }; signIn: { ...; }; signUp: { ...; }; }'.

TS2307: Cannot find module '@/pages/password-recovery/recaptcha' or its corresponding type declarations.

TS2307: Cannot find module '@/shared/assets/paths' or its corresponding type declarations.

После исправления запусти инспектор кода, вдруг есть еще.

**Comment by IrinaMartArm** [comment]
run build production

**Comment by IrinaMartArm** [comment]
run build production

**Comment by IrinaMartArm** [comment]
run build production

**Comment by IrinaMartArm** [comment]
run build production

**Comment by IrinaMartArm** [comment]
run build production

**Pull request merged**
