### PR TITLE
Fix: AddPhotoForm

### PR DESCRIPTION
**Pull request by GennadiiPaninov**

### CODE REVIEW

**Comment by GennadiiPaninov** [comment]
run build production

**Comment by IrinaMartArm** [comment]
run build production

**Comment by GennadiiPaninov** [comment]
run build production

**Comment by GennadiiPaninov** [comment]
run build production

**Comment by GennadiiPaninov** [comment]
run build production

**Comment by IrinaMartArm** [comment]
run build production

**Pull request merged**
